backend:
  name: git-gateway
  branch: main

media_folder: "docs/public/uploads/banners"
public_folder: "/uploads/banners"

collections:
  - name: "imagesConfig"
    label: "Startseiten-Konfiguration"
    files:
      - label: "Startseitenbild"
        name: "homepage"
        file: "docs/data/homepage.yml"
        fields:
          - { label: "Titel", name: "title", widget: "string" }
          - {
              label: "Bild-URL",
              name: "imageUrl",
              widget: "string",
              required: false,
            }
          - {
              label: "Upload Bild",
              name: "uploadImage",
              widget: "image",
              required: false,
            }

  - name: "banners"
    label: "Banner Management"
    folder: "docs/public/uploads/banners"
    create: true
    slug: "banner-{{year}}-{{month}}-{{day}}-{{hour}}-{{minute}}-{{slug}}"
    fields:
      - { label: "Banner Name", name: "name", widget: "string" }
      - { label: "Banner Bild", name: "image", widget: "image" }
      - { label: "Aktiv", name: "active", widget: "boolean", default: true }
      - {
          label: "Anzeige Reihenfolge",
          name: "order",
          widget: "number",
          default: 1,
        }
      - {
          label: "Beschreibung",
          name: "description",
          widget: "text",
          required: false,
        }
